### ISSUE TITLE
About dataInfoFile = open(r'dataset/trainInfo.txt','r') in model.py

### ISSUE THREAD

**Issue by Grape-A** [HeranYang/sc-cyclegan#1]
Hello, thank you very much for your open source. I encountered a problem when reproducing your paper. What information is stored in the trainInfo.txt file in model.py? Is it the id of the data? Can it be used explicitly

**Comment by HeranYang** [comment]
Thank you for your interest in our work. 
Each line in this txt file is the start and end sagittal slice ID of each subject, which is used to select the training slices. Besides, the blank slices is also removed. Since this file is just related to the data preparation part, you can prepare your own txt file based on your data, or you can also randomly select the input slices without using such file. 
Also, thank you for pointing out this problem. I will update the readme file and make it clear soon.

**Comment by Grape-A** [comment]
Thank you very much for your reply and guidance. I have been practicing abroad recently, and I will immediately reproduce the results according to your Suggestions when I return to school next week. If there are any problems, I hope you will give me your advice. Thanks again!
